<aside class="sidebar">
    <button type="button" class="sidebar-toggle-button" id="sidebarToggleButton" aria-label="Sembunyikan sidebar" title="Sembunyikan sidebar">‹</button>
    <div class="brand"><div class="brand-mark">MA</div><div class="brand-text"><div class="brand-name">MC ALMARA</div><div class="brand-subtitle">Money Changer Digital OS</div></div></div>
    <div class="tenant-box"><div class="tenant-label">TENANT</div><div class="tenant-name">{{ auth()->user()->tenant->name ?? 'MC Almara' }}</div></div>
    <nav class="sidebar-nav">
        <div class="nav-section"><div class="nav-section-title">WORKSPACE</div>
            <a href="{{ route('dashboard') }}" class="nav-item {{ request()->routeIs('dashboard') ? 'active' : '' }}"><span class="nav-icon">⌂</span><span class="nav-text">Dashboard</span></a>
            <a href="{{ route('transactions.create') }}" class="nav-item {{ request()->routeIs('transactions.*') ? 'active' : '' }}"><span class="nav-icon">⇄</span><span class="nav-text">Transaksi</span></a>
            <a href="{{ route('customers.index') }}" class="nav-item {{ request()->routeIs('customers.*') ? 'active' : '' }}"><span class="nav-icon">♙</span><span class="nav-text">Nasabah</span></a>
            <a href="{{ route('settings.compliance-threshold.index') }}" class="nav-item {{ request()->routeIs('settings.compliance-threshold.*') ? 'active' : '' }}"><span class="nav-icon">✓</span><span class="nav-text">KYC & Compliance</span></a>
        </div>
        <div class="nav-section"><div class="nav-section-title">TREASURY</div>
            <a href="{{ route('settings.currency-variants.index') }}" class="nav-item {{ request()->routeIs('settings.currency-variants.*') ? 'active' : '' }}"><span class="nav-icon">◎</span><span class="nav-text">Mata Uang</span></a>
            <a href="{{ route('settings.denominations.index') }}" class="nav-item {{ request()->routeIs('settings.denominations.*') ? 'active' : '' }}"><span class="nav-icon">▤</span><span class="nav-text">Pecahan</span></a>
            <a href="{{ route('settings.rates.index') }}" class="nav-item {{ request()->routeIs('settings.rates.*') ? 'active' : '' }}"><span class="nav-icon">↗</span><span class="nav-text">Stok Valas</span></a>
            <a href="{{ route('settings.rates.index') }}" class="nav-item {{ request()->routeIs('settings.rates.*') ? 'active' : '' }}"><span class="nav-icon">◉</span><span class="nav-text">Manajemen Kurs</span></a>
            <a href="{{ route('settings.bank-accounts.index') }}" class="nav-item {{ request()->routeIs('settings.bank-accounts.*') ? 'active' : '' }}"><span class="nav-icon">▣</span><span class="nav-text">Kas & Bank</span></a>
            <a href="{{ route('gantungan.index') }}" class="nav-item {{ request()->routeIs('gantungan.*') ? 'active' : '' }}"><span class="nav-icon">⊙</span><span class="nav-text">Gantungan</span></a>
            <a href="{{ route('closing.index') }}" class="nav-item {{ request()->routeIs('closing.*') ? 'active' : '' }}"><span class="nav-icon">◫</span><span class="nav-text">Closing Operasional</span></a>
        </div>
        <div class="nav-section"><div class="nav-section-title">MANAGEMENT</div>
            <a href="{{ route('settings.company.edit') }}" class="nav-item {{ request()->routeIs('settings.company.*') ? 'active' : '' }}"><span class="nav-icon">▥</span><span class="nav-text">Perusahaan</span></a>
            <a href="{{ route('settings.customer-risk.index') }}" class="nav-item {{ request()->routeIs('settings.customer-risk.*') ? 'active' : '' }}"><span class="nav-icon">▤</span><span class="nav-text">Master Customer Risk</span></a>
            <a href="{{ route('settings.iso-currencies.index') }}" class="nav-item {{ request()->routeIs('settings.iso-currencies.*') ? 'active' : '' }}"><span class="nav-icon">◎</span><span class="nav-text">ISO Currencies</span></a>
        </div>
    </nav>
    <div class="sidebar-footer"><button type="button" class="sidebar-user-button" id="sidebarUserButton" aria-expanded="false"><div class="footer-avatar">{{ strtoupper(substr(auth()->user()->name ?? 'U', 0, 1)) }}</div><div class="footer-user"><div class="footer-name">{{ auth()->user()->name ?? 'User' }}</div><div class="footer-role">{{ auth()->user()->roles()->first()->name ?? 'User' }}</div></div><div class="footer-logout">↪</div></button><div class="sidebar-user-menu" id="sidebarUserMenu"><div class="sidebar-user-menu-header"><div class="sidebar-user-menu-avatar">{{ strtoupper(substr(auth()->user()->name ?? 'U', 0, 1)) }}</div><div class="sidebar-user-menu-info"><div class="sidebar-user-menu-name">{{ auth()->user()->name ?? 'User' }}</div><div class="sidebar-user-menu-email">{{ auth()->user()->email ?? '' }}</div></div></div><div class="sidebar-user-menu-divider"></div><a href="#" class="sidebar-user-menu-item"><span class="menu-item-icon">👤</span><span>Profil Saya</span></a><a href="#" class="sidebar-user-menu-item"><span class="menu-item-icon">🏢</span><span>Tenant & Cabang</span></a><a href="{{ route('settings.company.edit') }}" class="sidebar-user-menu-item"><span class="menu-item-icon">⚙</span><span>Pengaturan</span></a><a href="#" class="sidebar-user-menu-item"><span class="menu-item-icon">🔐</span><span>Keamanan</span></a><div class="sidebar-user-menu-divider"></div><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="sidebar-user-menu-item logout-item"><span class="menu-item-icon">🚪</span><span>Keluar</span></button></form></div></div>
</aside>