@extends('layouts.app')

@section('content')
<style>
    .teller-page{padding:16px 20px 28px;background:#f7f9f8;min-height:calc(100vh - 70px)}
    .teller-header{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}
    .teller-title{font-size:21px;font-weight:700;margin:0;color:#26352e}.teller-subtitle{margin-top:3px;color:#77827d;font-size:12px}
    .teller-primary-btn{border:0;border-radius:6px;padding:8px 11px;font-weight:600;font-size:11px;background:#26352e;color:#fff;text-decoration:none;display:inline-flex;align-items:center;gap:6px}.teller-primary-btn:hover{color:#fff;opacity:.9}
    .teller-stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:10px}.teller-stat{background:#fff;border:1px solid #dfe7e2;border-radius:6px;padding:9px 11px}.teller-stat-label{color:#78837e;font-size:9px;text-transform:uppercase;letter-spacing:.04em}.teller-stat-value{font-size:17px;font-weight:700;color:#26352e;margin-top:2px}.teller-stat-note{font-size:9px;color:#9aa39f;margin-top:1px}
    .teller-filter{background:#fff;border:1px solid #dfe7e2;border-radius:6px;padding:9px 11px;margin-bottom:10px}.teller-filter form{display:flex;align-items:end;gap:8px;flex-wrap:nowrap}.teller-filter-field{flex:0 0 auto}.teller-filter-search{flex:1 1 420px;min-width:260px}.teller-filter-status{flex:0 0 170px}.teller-filter-date{flex:0 0 150px}.teller-filter-actions{display:flex;gap:5px;flex:0 0 auto}.teller-filter-label{font-size:9px;font-weight:700;color:#65716b;margin-bottom:3px}.teller-filter .form-control,.teller-filter .form-select{min-height:31px;height:31px;border-radius:5px;font-size:11px;padding:4px 7px;border-color:#d5ded9}.teller-filter .btn{min-height:31px;height:31px;font-size:10px;padding:4px 9px;border-radius:5px;white-space:nowrap}
    .teller-table-card{background:#fff;border:1px solid #dfe7e2;border-radius:6px;overflow:hidden}.teller-table-header{padding:9px 11px;border-bottom:1px solid #dfe7e2;display:flex;justify-content:space-between;align-items:center}.teller-table-title{font-size:12px;font-weight:700;color:#26352e;margin:0}.teller-table-count{color:#7d8883;font-size:9px}
    .teller-table{margin:0;width:100%;border-collapse:collapse}.teller-table th{background:#f4f7f5;color:#68746e;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;padding:6px 7px;border:1px solid #dfe7e2;white-space:nowrap}.teller-table td{padding:6px 7px;border:1px solid #dfe7e2;vertical-align:middle;color:#405049;font-size:11px}.teller-table tbody tr:hover{background:#f8fbf9}
    .transaction-no{font-weight:700;color:#26352e;font-size:11px}.transaction-id{font-size:8px;color:#9aa39f;margin-top:2px;word-break:break-all}.customer-name{font-weight:600;color:#33423b}.customer-number{font-size:8px;color:#94a09a;margin-top:2px}.item-row{display:flex;align-items:center;gap:4px;margin-bottom:2px}.item-row:last-child{margin-bottom:0}.direction-badge{font-size:8px;font-weight:700;padding:2px 4px;border-radius:3px;min-width:30px;text-align:center}.direction-buy{background:#e4f2e9;color:#25633e}.direction-sell{background:#f7e5e5;color:#8b3434}.currency-code{font-weight:700;color:#33423b}.quantity{color:#52605a}.settlement-line{margin-bottom:2px}.settlement-line:last-child{margin-bottom:0}.settlement-label{color:#94a09a;font-size:8px;text-transform:uppercase;font-weight:700}.settlement-value{font-weight:600;color:#405049}.status-badge{display:inline-flex;align-items:center;border:1px solid #d5dfda;border-radius:4px;padding:2px 5px;font-size:8px;font-weight:700;white-space:nowrap}.status-completed{background:#e5f2e9;color:#25633e}.status-paid{background:#e7eef8;color:#315f91}.status-pending{background:#f7f0dc;color:#85651e}.status-cancelled,.status-draft{background:#f1f4f2;color:#59665f}.status-rejected{background:#f7e5e5;color:#8b3434}.settlement-status{font-size:8px;color:#94a09a;margin-top:3px}.teller-action{border:1px solid #d5ded9;background:#fff;color:#405049;border-radius:4px;padding:3px 6px;font-size:8px;font-weight:600;text-decoration:none;white-space:nowrap}.teller-action:hover{background:#f4f7f5;color:#26352e}.teller-empty{padding:50px 20px;text-align:center;color:#94a09a}.teller-empty-title{font-weight:600;color:#64716a;margin-bottom:2px}.teller-pagination{padding:8px 11px;border-top:1px solid #dfe7e2}
    @media(max-width:900px){.teller-filter form{flex-wrap:wrap}.teller-filter-search{flex:1 1 100%}.teller-filter-status,.teller-filter-date{flex:1 1 180px}.teller-filter-actions{flex:0 0 auto}}@media(max-width:1100px){.teller-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:768px){.teller-page{padding:12px}.teller-header{align-items:flex-start}.teller-table-card{overflow-x:auto}.teller-table{min-width:900px}}@media(max-width:480px){.teller-stat-grid{grid-template-columns:1fr}}
</style>
<div class="teller-page">
    <div class="teller-header"><div><h1 class="teller-title">Teller</h1><div class="teller-subtitle">Operasional transaksi Money Changer</div></div><a href="{{ route('transactions.create') }}" class="teller-primary-btn"><span>+</span><span>Transaksi Baru</span></a></div>
    @if(session('success'))<div class="alert alert-success py-2 px-3 mb-2" style="font-size:11px">{{ session('success') }}</div>@endif
    @if($errors->has('transaction'))<div class="alert alert-danger py-2 px-3 mb-2" style="font-size:11px">{{ $errors->first('transaction') }}</div>@endif
    @php $todayTransactions=$transactions->total(); $pendingCount=$transactions->getCollection()->where('status','pending_payment')->count(); $paidCount=$transactions->getCollection()->where('status','paid')->count(); $completedCount=$transactions->getCollection()->where('status','completed')->count(); @endphp
    <div class="teller-stat-grid"><div class="teller-stat"><div class="teller-stat-label">Transaksi</div><div class="teller-stat-value">{{ number_format($todayTransactions,0,',','.') }}</div><div class="teller-stat-note">Hasil pencarian aktif</div></div><div class="teller-stat"><div class="teller-stat-label">Pending Payment</div><div class="teller-stat-value">{{ number_format($pendingCount,0,',','.') }}</div><div class="teller-stat-note">Menunggu pembayaran</div></div><div class="teller-stat"><div class="teller-stat-label">Paid</div><div class="teller-stat-value">{{ number_format($paidCount,0,',','.') }}</div><div class="teller-stat-note">Pembayaran terkonfirmasi</div></div><div class="teller-stat"><div class="teller-stat-label">Completed</div><div class="teller-stat-value">{{ number_format($completedCount,0,',','.') }}</div><div class="teller-stat-note">Transaksi selesai</div></div></div>
    <div class="teller-filter"><form method="GET" action="{{ route('teller.index') }}"><div class="teller-filter-field teller-filter-search"><div class="teller-filter-label">Cari Transaksi / Customer</div><input type="text" name="search" class="form-control" placeholder="Nomor transaksi, nama, customer, nomor HP..." value="{{ request('search') }}"></div><div class="teller-filter-field teller-filter-status"><div class="teller-filter-label">Status</div><select name="status" class="form-select"><option value="">Semua Status</option><option value="draft" {{ request('status')==='draft'?'selected':'' }}>Draft</option><option value="pending_payment" {{ request('status')==='pending_payment'?'selected':'' }}>Pending Payment</option><option value="paid" {{ request('status')==='paid'?'selected':'' }}>Paid</option><option value="completed" {{ request('status')==='completed'?'selected':'' }}>Completed</option><option value="cancelled" {{ request('status')==='cancelled'?'selected':'' }}>Cancelled</option><option value="rejected" {{ request('status')==='rejected'?'selected':'' }}>Rejected</option></select></div><div class="teller-filter-field teller-filter-date"><div class="teller-filter-label">Tanggal</div><input type="date" name="date" class="form-control" value="{{ request('date') }}"></div><div class="teller-filter-actions"><button type="submit" class="btn btn-dark">Filter</button><a href="{{ route('teller.index') }}" class="btn btn-outline-secondary">Reset</a></div></form></div>
    <div class="teller-table-card"><div class="teller-table-header"><div><h5 class="teller-table-title">Transaksi</h5><div class="teller-table-count">Menampilkan {{ $transactions->count() }} dari {{ $transactions->total() }} transaksi</div></div></div><div class="table-responsive"><table class="teller-table"><thead><tr><th>Transaksi</th><th>Customer</th><th>Item</th><th>Settlement</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
    @forelse($transactions as $transaction)
        <tr><td><div class="transaction-no">{{ $transaction->transaction_no }}</div><div class="transaction-id">{{ $transaction->transaction_date?->format('d/m/Y H:i') }}</div></td><td><div class="customer-name">{{ $transaction->customer?->full_name ?? '-' }}</div><div class="customer-number">{{ $transaction->customer?->customer_number ?? '-' }}</div></td><td>@forelse($transaction->items as $item)<div class="item-row"><span class="direction-badge {{ $item->direction==='buy'?'direction-buy':'direction-sell' }}">{{ strtoupper($item->direction) }}</span><span class="currency-code">{{ $item->currency?->code ?? '-' }}</span><span class="quantity">{{ $item->quantity }}</span></div>@empty<span class="text-muted">-</span>@endforelse</td><td>@forelse($transaction->settlements as $settlement)<div class="settlement-line"><span class="settlement-label">{{ $settlement->settlement_type ?? 'TOTAL' }}</span> <span class="settlement-value">{{ $settlement->amount !== null ? number_format((float)$settlement->amount,2,',','.') : '-' }}</span></div>@empty<span class="text-muted">-</span>@endforelse<div class="settlement-status">{{ $transaction->settlement_status }}</div></td><td><span class="status-badge status-{{ str_replace('_','-',$transaction->status) }}">{{ strtoupper(str_replace('_',' ',$transaction->status)) }}</span></td><td><span class="text-muted" style="font-size:9px">Detail menyusul</span></td></tr>
    @empty
        <tr><td colspan="6"><div class="teller-empty"><div class="teller-empty-title">Belum ada transaksi</div><div>Buat transaksi baru untuk memulai operasional teller.</div></div></td></tr>
    @endforelse
    </tbody></table></div><div class="teller-pagination">{{ $transactions->links() }}</div></div>
</div>
@endsection
