@extends('layouts.app')
@section('content')
<div class="container-fluid py-4">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Gantungan</h1><div class="text-muted small">Daftar uang/tagihan yang masih outstanding dan akan masuk rekonsiliasi Closing.</div></div><a href="{{ route('gantungan.create') }}" class="btn btn-dark">+ Gantungan Baru</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card shadow-sm border-0"><div class="card-body"><div class="small text-muted">Outstanding Aktif</div><div class="fs-4 fw-bold">Rp {{ number_format($summary['open'],0,',','.') }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm border-0"><div class="card-body"><div class="small text-muted">Jumlah Aktif</div><div class="fs-4 fw-bold">{{ $summary['count'] }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm border-0"><div class="card-body"><div class="small text-muted">Total Sudah Dilunasi</div><div class="fs-4 fw-bold">Rp {{ number_format($summary['settled'],0,',','.') }}</div></div></div></div></div>
<div class="card shadow-sm border-0"><div class="card-body"><form class="row g-2 mb-3"><div class="col-md-3"><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Cari nomor/judul/PIC"></div><div class="col-md-2"><select name="status" class="form-select"><option value="">Semua Status</option><option value="open" @selected(request('status')==='open')>Open</option><option value="partial" @selected(request('status')==='partial')>Partial</option><option value="settled" @selected(request('status')==='settled')>Settled</option></select></div><div class="col-md-2"><select name="category" class="form-select"><option value="">Semua Kategori</option><option value="employee">Karyawan</option><option value="branch">Cabang/Tempat Lain</option><option value="supplier">Supplier</option><option value="operational">Operasional</option><option value="other">Lainnya</option></select></div><div class="col-md-2"><input type="date" name="date" value="{{ request('date') }}" class="form-control"></div><div class="col-md-2"><button class="btn btn-outline-dark">Filter</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>No</th><th>Tanggal</th><th>Kategori</th><th>Judul</th><th>PIC</th><th class="text-end">Nominal</th><th class="text-end">Outstanding</th><th>Status</th></tr></thead><tbody>
@forelse($gantungans as $item)<tr><td><a href="{{ route('gantungan.show',$item) }}">{{ $item->gantungan_no }}</a></td><td>{{ $item->business_date?->format('d/m/Y') }}</td><td>{{ ['employee'=>'Karyawan','branch'=>'Cabang/Tempat Lain','supplier'=>'Supplier','operational'=>'Operasional','other'=>'Lainnya'][$item->category] ?? $item->category }}</td><td>{{ $item->title }}</td><td>{{ $item->counterparty_name ?: '-' }}</td><td class="text-end">Rp {{ number_format($item->amount,0,',','.') }}</td><td class="text-end fw-semibold">Rp {{ number_format($item->outstanding_amount,0,',','.') }}</td><td><span class="badge text-bg-{{ $item->status==='settled'?'success':($item->status==='partial'?'warning':'secondary') }}">{{ strtoupper($item->status) }}</span></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">Belum ada data Gantungan.</td></tr>@endforelse
</tbody></table></div>{{ $gantungans->links() }}</div></div></div>
@endsection
